### ISSUE TITLE
[IDEA] Supla device simulator

### ISSUE THREAD

**Issue by nextMJ** [SUPLA/supla-arduino#30]
Hi,
I have an idea (and am willing with trying to implement it) and would like to know if you are interested in joining it into this project. I would like to develop a device built on this library but it is very difficult to develop when I'm not around this device. For such a purpose I would like to create PC simulator based on this library. Problem is that most of the classes in this library is dependent on "Arduino" general library. But from what I have seen (feel free to correct me) most of the time it is used due to logging purposses. Due to that I would change the logging from simple _Serial.print_ to something like _Logger.log_ and the Logger would choose appropriate logging mechanism based on where it is running. I would choose Singleton and Factory mechanism for creating and accessing this "general" instance of Logger.

@przemyslawzygmunt Would you like me to try implement this feature into this library? :-) If not, feel free to close this issue.

**Comment by nextMJ** [comment]
@klew What do you think? :-)

**Comment by klew** [comment]
There are few other Arduino specific methods, not only logging.
It is usually fairy simple to get rid of those function calls, by providing your own "empty" implementation. I.e. like it is done in extras/test, where lib is build (partially) and tested on standard PC.

supla-common folder already provides log.h interface for supla_log methods. Those type of logs are sometimes used in library, however not everywhere, since it didn't support printing of some types that were supported by Arduino's Serial. Additionally there is no support for F() macro in supla_log (which puts text in flash memory and don't put it by default in RAM - this is used to save memory allocation which is a problem on Arduino Mega board).

So from my point of view, you could extend supla_log to support missing parts and move whole logging in lib to supla_log. However please arrange it first with @przemyslawzygmunt
